# Generated by Django 4.1 on 2022-09-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_product_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="content",
            new_name="description",
        ),
        migrations.AddField(
            model_name="product",
            name="author",
            field=models.CharField(default="Unknown", max_length=255),
        ),
    ]
